language: generic

jobs:
  include:
    - os: linux
      name: "Linux"
      dist: bionic

addons:
  apt:
    packages:
      - bsdtar

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm

# Do not run in Travis CI when the branch name starts with "nobuild". Primarily
# intended for documentation updates but may be used as an escape hatch for
# other purposes.
branches:
  except:
    - /^nobuild.*$/

services:
  - docker

env:
  global:
    - DEV_REGISTRY=quay.io/datawire-dev
    - RELEASE_REGISTRY=quay.io/datawire
    # - DBUILD_ARGS="--cache-from ${DEV_REGISTRY}/builder:latest"

    # Set from the repository settings:
    #- DOCKER_BUILD_USERNAME=[secure] (optional)
    #- DOCKER_BUILD_PASSWORD=[secure] (optional)
    #- DOCKER_RELEASE_USERNAME=[secure]
    #- DOCKER_RELEASE_PASSWORD=[secure]

    # Encrypted here:
    # - PACKAGECLOUD_TOKEN # XXX: remove me
    # - PYPI_PASSWORD      # XXX: remove me
    # - AWS_ACCESS_KEY_ID
    # - AWS_SECRET_ACCESS_KEY
    - secure: "F9oY34UDI8aXuZ9nb6z3/ltlqrNs4RUQHDZHa2YSFoq0r2Rn272Yg7oHfPh3deYNKxtUOBwwcpiC/7G9MqhkuLQEYhqY/KowidG6gOxCZdTDEVS10C4GDEMGj64URlUCS722tQYMIpniiB6LW2kEOOcEuzC6JsVxS7BowUEVk7Ly8BTzrgNuGFN2bSphRyrJyrS3Reo5a1YI3joUMzI29t7fegefTIHHONKhZpIE86wFRk11nwvJdt54Eu9dVFwiEiGW9L9SnG2ph4UiqN6z3iQFCQ8HNvnf+BvNasdMBR3f85DPnG/syqOcQrrE1e5T88UXRxyUwR2ty1ad+ZvQPggwsoFs1FmdJH04pGn0Tgpo/AHNe5c67tvDbw2W4jlFJgVI/keoFvQigSM2DUuL1i0v48TkZw8lgcfasRjtJi7iDTC4qqjyMLkY6y2TRTVDG/86qxK3No7vvJZajzntU3c6MUttiSDubaHL5RuklQ+7MjN5Dp1cD09L3Qqnm9KcjWzbNoyqriBO84VU4aJFF72jJ18qADX/UUj7cxi0ShY19BHX2Vrp3pPSNiePfO7okUrg5Wc4eD7u4eC+aUVHboEX35NhBnfj7/ASrsltIANYFmNarv3tvd67JIsm/Wz3pge6YOSV1pBr2IsGk5UVIXdJ/mm6GVWFlJ9PiELDBGc="

install:
  - ./releng/travis-install.sh
  # Adjust the environment per travis-install.sh
  - PATH=~/bin:$PATH
  - source ~/.gimme/envs/latest.env
  - export DEV_KUBECONFIG=~/.kube/$(cat ~/kubernaut-claim.txt).yaml

script:
  - docker pull ${DEV_REGISTRY}/builder:latest
  - ./releng/travis-script.sh

after_script:
  # release the kubernaut claim
  - ./releng/travis-cleanup.sh
  # - docker tag builder:latest ${DEV_REGISTRY}/builder:latest && docker push ${DEV_REGISTRY}/builder:latest
