---
language: generic

branches:
  only:
  - master
  - early-access

deploy:
  - provider: script
    script: ./publish-website.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./publish-website.sh
    skip_cleanup: true
    on:
      branch: early-access
